use_frameworks!

platform :ios, '8.0'

target 'WKLaunch_Example' do
  pod 'WKLaunch', :path => '../'

  target 'WKLaunch_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
